channels:
  - mvdbeek
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cmake=3.14.0
  - ipython=7.8.0
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - make=4.2.1
  - ncurses=6.1
  - python=3.6.8
  - pytest=5.2.0
  - pytest-forked=1.1.3
  - pytest-xdist=1.30.0
  - setuptools_scm==4.1.2
