channels:
  - mvdbeek
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cmake=3.14.0
  - glib=2.56.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jinja2=2.10.1
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - make=4.2.1
  - matplotlib=3.1.1
  - notebook=6.0.1
  - numpy=1.19.5
  - pip=21.0.1
  - pylint=2.4.2
  - pytest=5.2.0
  - pytest-xdist=1.30.0
  - python=3.7
  - pip:
    - absl-py==0.10
    - aenum==2.2.4
    - astor==0.8.1
    - black==19.10b0
    - dill==0.3.1.1
    - flatbuffers==1.12.0
    - h5py==2.10.0
    - scipy==1.4.1
    - setuptools==54.1.1
    - setuptools_scm==4.1.2
    - tensorflow==2.4.1
    - typing-extensions==3.7.4
    - wheel==0.35
    - -e ./xcore_interpreters
